"""Provider-neutral model contracts shipped with Purrcept Core."""

from ._utils import JsonObject, JsonPrimitive, JsonValue
from .backend import ModelBackend, ModelEventSink
from .caching import CacheMode, PromptCachePolicy, PromptStability
from .conformance import (
    BackendConformanceCase,
    BackendConformanceError,
    BackendConformanceReport,
    BackendConformanceResult,
    BackendConformanceScenario,
    BackendConformanceStep,
    BackendScenarioFactory,
    run_backend_conformance,
)
from .content import (
    ContentBlock,
    ImageBlock,
    ImageBytes,
    ImageUrl,
    ReasoningBlock,
    TextBlock,
    ToolCallBlock,
    ToolResultBlock,
)
from .context_policy import (
    AppendOnlyContext,
    ContextBudgetExceededError,
    ContextPolicy,
    PreparedContext,
    RequestTokenBudget,
    RequestTokenCounter,
    SlidingWindowContext,
    TokenBudgetContext,
    TokenCounter,
)
from .continuation import ContinuationPolicy, ModelContinuation
from .conversation import Conversation, ConversationCheckpoint, ConversationState
from .effects import Generate
from .errors import (
    ModelAuthenticationError,
    ModelContextWindowError,
    ModelError,
    ModelRateLimitError,
    ModelRequestError,
    ModelTransientError,
    ModelUnavailableError,
)
from .instructions import SystemInstruction
from .loop import ConversationBusyError, ModelTurnResult, ToolLoopLimitError
from .messages import Message, MessageRole
from .model import Model
from .prompt import (
    CompiledPrompt,
    PromptCompiled,
    PromptCompileError,
    PromptCompiler,
    PromptDefinitionError,
    PromptDiagnostics,
    PromptDraft,
    PromptError,
    PromptLibrary,
    PromptRenderError,
    PromptTemplate,
    PromptTraceEvent,
    PromptTraceSink,
    PromptTransform,
    ReminderConsumed,
    ReminderSourceFailed,
    ReminderSourceResolved,
    RenderPolicy,
    UnknownPromptError,
    header,
    is_effectively_empty,
    join_blocks,
    min_len,
    optional,
    trim,
    wrap,
)
from .reminder_sources import ReminderResolutionContext, ReminderSource
from .reminders import ReminderPlacement, ReminderScope, ReminderState, SystemReminder
from .requests import ModelRequest, ToolSpec
from .responses import FinishReason, ModelResponse, TokenUsage
from .settings import ModelSettings, ToolChoice
from .streaming import (
    ModelStreamCompleted,
    ModelStreamEvent,
    ModelStreamStarted,
    TextDelta,
    ToolCallDelta,
    UsageUpdate,
)
from .tools import (
    FunctionTool,
    InvokeTool,
    SyncToolPolicy,
    ToolArgumentsError,
    ToolContext,
    ToolDefinitionError,
    ToolErrorPolicy,
    ToolLike,
    ToolParameter,
    ToolResult,
    ToolResultEncodingError,
    ToolSet,
    UnknownToolError,
    tool,
)

__all__ = [
    "AppendOnlyContext",
    "BackendConformanceCase",
    "BackendConformanceError",
    "BackendConformanceReport",
    "BackendConformanceResult",
    "BackendConformanceScenario",
    "BackendConformanceStep",
    "BackendScenarioFactory",
    "CacheMode",
    "CompiledPrompt",
    "ContentBlock",
    "ContextBudgetExceededError",
    "ContextPolicy",
    "ContinuationPolicy",
    "Conversation",
    "ConversationBusyError",
    "ConversationCheckpoint",
    "ConversationState",
    "FinishReason",
    "FunctionTool",
    "Generate",
    "ImageBlock",
    "ImageBytes",
    "ImageUrl",
    "InvokeTool",
    "JsonObject",
    "JsonPrimitive",
    "JsonValue",
    "Message",
    "MessageRole",
    "Model",
    "ModelAuthenticationError",
    "ModelBackend",
    "ModelContextWindowError",
    "ModelContinuation",
    "ModelError",
    "ModelEventSink",
    "ModelRateLimitError",
    "ModelRequest",
    "ModelRequestError",
    "ModelResponse",
    "ModelSettings",
    "ModelStreamCompleted",
    "ModelStreamEvent",
    "ModelStreamStarted",
    "ModelTransientError",
    "ModelTurnResult",
    "ModelUnavailableError",
    "PreparedContext",
    "PromptCachePolicy",
    "PromptCompileError",
    "PromptCompiled",
    "PromptCompiler",
    "PromptDefinitionError",
    "PromptDiagnostics",
    "PromptDraft",
    "PromptError",
    "PromptLibrary",
    "PromptRenderError",
    "PromptStability",
    "PromptTemplate",
    "PromptTraceEvent",
    "PromptTraceSink",
    "PromptTransform",
    "ReasoningBlock",
    "ReminderConsumed",
    "ReminderPlacement",
    "ReminderResolutionContext",
    "ReminderScope",
    "ReminderSource",
    "ReminderSourceFailed",
    "ReminderSourceResolved",
    "ReminderState",
    "RenderPolicy",
    "RequestTokenBudget",
    "RequestTokenCounter",
    "SlidingWindowContext",
    "SyncToolPolicy",
    "SystemInstruction",
    "SystemReminder",
    "TextBlock",
    "TextDelta",
    "TokenBudgetContext",
    "TokenCounter",
    "TokenUsage",
    "ToolArgumentsError",
    "ToolCallBlock",
    "ToolCallDelta",
    "ToolChoice",
    "ToolContext",
    "ToolDefinitionError",
    "ToolErrorPolicy",
    "ToolLike",
    "ToolLoopLimitError",
    "ToolParameter",
    "ToolResult",
    "ToolResultBlock",
    "ToolResultEncodingError",
    "ToolSet",
    "ToolSpec",
    "UnknownPromptError",
    "UnknownToolError",
    "UsageUpdate",
    "header",
    "is_effectively_empty",
    "join_blocks",
    "min_len",
    "optional",
    "run_backend_conformance",
    "tool",
    "trim",
    "wrap",
]
